# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-core:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i --workspaces
      - run: npm run lint:check -w packages/core --if-present
      - run: npm run format:check -w packages/core --if-present
      - run: npm run build -w packages/core --if-present
      - run: npm test -w packages/core --if-present

  build-tag:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm --prefix ./packages/tag install
      - run: npm run lint:check -w packages/tag --if-present
      - run: npm run format:check -w packages/tag --if-present
      - run: npm --prefix ./packages/tag run build --if-present
      - run: npm --prefix ./packages/tag test --if-present

  build-with-sprinkles:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm --prefix ./packages/with-sprinkles install
      - run: npm run lint:check -w packages/with-sprinkles --if-present
      - run: npm run format:check -w packages/with-sprinkles --if-present
      - run: npm --prefix ./packages/with-sprinkles run build --if-present
      - run: npm --prefix ./packages/with-sprinkles test --if-present
